[tox]
envlist = py38{,-server610},py314


[testenv]
commands = py.test --cov {envsitepackagesdir}/devpi_findlinks {posargs:tests}
deps =
    webtest
    mock
    pytest
    pytest-cov
    server610: devpi-server==6.10.0
    server610: setuptools<82


[pytest]
addopts =
    --cov-report=term
    --cov-report=html
    -r a
    -W once::DeprecationWarning
    -W ignore:"`pyramid.compat` is deprecated":DeprecationWarning
    -W ignore:"Accessing argon2.__version__":DeprecationWarning
    -W ignore:"Deprecated call to `pkg_resources.declare_namespace":DeprecationWarning
    -W ignore:"pkg_resources is deprecated":DeprecationWarning
    -W once:"'cgi' is deprecated":DeprecationWarning
    -W once:"'crypt' is deprecated":DeprecationWarning
    -W once:"setDaemon() is deprecated":DeprecationWarning
    -W once:"The 'op_sro":DeprecationWarning
    -W once::pytest.PytestDeprecationWarning
    -W once::ResourceWarning
testpaths =
    devpi_findlinks
    tests
